---
- name: add docker apt repo
  sudo: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: add docker repo
  sudo: yes
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: install docker
  sudo: yes
  apt: name="{{ item }}" update_cache=yes
  with_items:
    - lxc-docker
    - lxc-docker-1.6.1

- name: ensure docker is linked
  sudo: yes
  file:
    src: /usr/bin/docker
    dest: /usr/local/bin/docker
    state: link

- name: install docker-py
  sudo: yes
  pip: name=docker-py version=1.1.0
