---
- name: Add docker apt repo key
  sudo: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add docker repo
  sudo: yes
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: Install docker
  sudo: yes
  apt: name="{{ item }}" update_cache=yes
  with_items:
    - lxc-docker
    - lxc-docker-1.6.0

- name: ensure docker is linked
  sudo: yes
  shell: ln -sf /usr/bin/docker.io /usr/local/bin/docker creates=/usr/local/bin/docker

- name: Install Docker Python library.
  sudo: yes
  pip: name=docker-py version=1.1.0
