---
- name: update apt cache if needed
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  sudo: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - git
    - python
    - python-dev
    - python3
    - python3-dev
    - python-virtualenv
    - python-setuptools
    - openssh-server

- name: install latest pip
  sudo: yes
  shell: 'easy_install -U pip'

- name: add groups
  sudo: yes
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo
    - admin
    - vboxusers
    - developers
    - deploy

- include: users.yml
