---
- include_vars: secrets.yml

- name: create deploy key
  sudo: yes
  copy:
    src: /Users/dharrigan/.ssh/davidharrigan.net/id_rsa
    dest: /home/deploy/.ssh/davidharrigan.net.private
    owner: deploy
    group: admin
    mode: 0644

- name: clone repo
  sudo: yes
  git:
    repo: git@github.com:davidharrigan/davidharrigan.net.git
    key_file: /home/deploy/.ssh/davidharrigan.net.private
    dest: /var/www/apps/davidharrigan.net
    accept_hostkey: True
    version: 0.0.6
  register: gitclone
  tags:
    - deploy

# TODO: pull from docker registry
# TODO: only build if we have to
- name: build container for davidharrigan.net application
  sudo: yes
  shell: 'cd /var/www/apps/davidharrigan.net; {{ item }}'
  with_items:
    - make build_app
  tags:
    - deploy
  when: gitclone.changed

# TODO: secrets
- name: ensure the container is running
  sudo: yes
  docker:
    name: app
    image: app
    state: reloaded
    ports:
    - "8080:8080"
    env:
      GCAPTCHA_SECRET: '{{ gcaptcha_secret }}'
      GMAIL_USER: '{{ gmail_user }}'
      GMAIL_PASS: '{{ gmail_pass }}'
  tags:
    - deploy
